help :-
    nl,
    write("************ DIRECTIONS *************"),nl,
    write("h — Aller sur la carte du haut"),nl,
    write("b — Aller sur la carte du bas"),nl,
    write("g — Aller sur la carte de gauche"),nl,
    write("h — Aller sur la carte de droite"),nl,
    nl,
    write("******* DÉPLACEMENTS SPÉCIAUX *******"),nl,
    write("surf 		  — Utiliser la capacité surf si c’est possible"),nl,
    write("tunnel 		  — Utiliser la capacité tunnel si c’est possible"),nl,
    write("vol(NOM_VILLE)    — Utiliser la capacité vol"),nl,
    write("rouler(DIRECTION) — Utiliser le vélo sur les pistes cyclables"),nl,
    nl,
    write("************ INFORMATIONS ***********"),nl,
    write("dec — Décrire le lieu actuel"),nl,
    write("pos — Obtenir des informations sur ce qu’il y a autour"),nl,
    write("e   — Afficher les pokemons de l’équipe"),nl,
    write("s   — Afficher le contenu du sac"),nl,
    nl,
    write("*************** OBJETS **************"),nl,
    write("ram		   — Ramasser un objet par terre"),nl,
    write("pokeflute	   — Jouer de la pokeflûte"),nl,
    write("reparer_velo	   — Repare le velo"),nl,
    write("donner(baie)	   — Donner une baie"),nl,
    write("demander(pokeball) — Demander une nouvelle pokeball au professeur Chen"),nl,
    nl,
    write("************** ACTIONS **************"),nl,
    write("c 		       — Capturer le pokemon"),nl,
    write("fouiller	       — Fouiller le lieu actuel"),nl,
    write("echanger	       — Echange de pokemon"),nl,
    write("faire_evoluer(POKEMON) — Faire évoluer un pokemon"),nl,
    nl,
    write("************** COMBAT ***************"),nl,
    write("attaquer_avec(POKEMON) — Attaque le pokemon d’un dresseur avec un pokemon de l’équipe"),nl,
    write("soigner                — Soigne les pokemons KO"),nl,nl.